export const PUBLIC_ENVIRONMENT_VARIABLE_NAMES = [
  'VITE_API_BASE_URL',
  'VITE_API_ORIGIN',
  'VITE_APP_ENVIRONMENT',
  'VITE_REQUEST_TIMEOUT_MS',
  'VITE_HEALTH_TIMEOUT_MS',
  'VITE_MAX_MESSAGE_LENGTH',
  'VITE_MAX_RESPONSE_LENGTH',
  'VITE_MAX_CONTEXT_MESSAGES',
  'VITE_MAX_PERSISTED_MESSAGES',
  'VITE_DEPLOYMENT_REPOSITORY',
] as const;

export type PublicEnvironmentVariableName =
  (typeof PUBLIC_ENVIRONMENT_VARIABLE_NAMES)[number];
